### DISCUSSION TITLE
Consider "extended" yaml workflows

### DISCUSSION THREAD

**Discussion by jwildfire** [Gilead-Public/gsm#1516] [General]
# Overview

I'm thinking about extending our yaml workflow functionality to simplify help standardize some of core `gsm` use cases. 

# Background 

When we started the package,`gsm` was built as a series of domain specific `assessments` that utilized our [standard assessmen data pipeline](https://gilead-biostats.github.io/gsm/articles/DataPipeline.html#assessment-data-pipeline) e.g. [ae_assess](https://github.com/Gilead-BioStats/gsm/blob/dev/R/AE_Assess.R)).  

We then extended this assessment framework with `workflows` (via [https://github.com/Gilead-BioStats/gsm/blob/dev/R/util-RunWorkflow.R]) that combined `filter`,`map` and  `assess` functions, that allowed for more realistic generation of a single KRI from raw data. 

Next, we extended the `workflow` framework to include `snapshots`  via [`makeSnapshot()`](https://github.com/Gilead-BioStats/gsm/blob/dev/R/Make_Snapshot.R). Snapshots allowed us to run multiple workflows on a single study using shared data and metadata. `snapshots` also added in study metadata, which is used in various (not entirely transparent) ways throughout {gsm}. 

There were lots of good reasons for this progression, but as we've used the package "in production" more over the last year, it's become pretty clear that the main use case is automated generation of study level snapshots on a regular basis. We're doing that a lot already, and will be doing more and more in coming years. It's much less common to run a standalone `assessment` (e.g. a programmer our mapping/assessment functions or a non-bundled `workflow`. 

# Extending workflows

Let's consider combining the existing  `assess`, `workflow` and `snapshot` processes into a single revised workflow process. Instead of a the current highly parameterized `AE_Assess()` function, we could have a standard `ae.yaml` file that would extend the existing `kri0001.yaml`; Instead of parameterizing AE_Assess, users would customize the yaml as needed. 

The default for this new combined workflow might look something like: 

```
file: ae.yaml
workflowid: kri0001
group: site
abbreviation: AE
metric: Adverse Event Rate
numerator: Adverse Events
denominator: Days on Study
model: Normal Approximation
score: Adjusted Z-Score
steps:
  - name: FilterDomain
    inputs: dfSUBJ
    output: dfSUBJ
    params:
      strDomain: dfSUBJ
      strColParam: strEnrollCol
      strValParam: strEnrollVal
  - name: AE_Map_Raw
    inputs:
      - dfAE
      - dfSUBJ
    output: dfInput
  - name: Transform_Rate
    inputs: dfInput 
    output: dfTransformed
    params:
      strGroup: "Site"
  - name: Analyze_NormalApprox
    inputs: dfTransformed 
    output: dfAnalyzed
 - name: Flag_NormalApprox
    inputs: dfAnalyzed
    output: dfFlagged
 - name: Summarize
   inputs: dfFlagged
   outputs: dfSummary
```

Notes/future work: 

- Can add params as needed ... 
- This could also be extended to add charts. Leaving that out for right now. 
- Could also be extended to support a new numerator/denominator mapping per #1506. #1516 

Going to test this out in the current framework ...

**Comment by jwildfire** [comment]
Not running right now because only certain functions are supported in [`RunStep()`](https://github.com/Gilead-BioStats/gsm/blob/f4b0e8ec9b7a71cd74a7a54e1f63dfe211c49d9d/R/util-RunStep.R#L49-L62). should be pretty straight forward to generalize though ...

**Reply by jwildfire** [reply]
Very basic implementation working in #1517. There are probably a few major questions to answer before we consider moving forward with a full implementation: 

- How do we run charts? 
- How do we run reports? 
- Does this support the mapping refactor from #1506 
- How do we run multiple workflows for a study?
 
Will try to work on those in the PR in the coming days ...

**Reply by jwildfire** [reply]
Charts up and running in #1517.

**Comment by jwildfire** [comment]
Added a [commit](https://github.com/Gilead-BioStats/gsm/pull/1517/commits/7a40786ab6359b6b36bb865708b7db25d89943ed) in #1517 with the revised Mapping framework outlined in #1506. New functions are: 
- `RunQuery()` which allows for basic sql transforms to be included as part of workflows
- `Make_Input_Rate()` which is a standardized merge for creating dfInput for Rates. 


I *think* these can be combined to replace all of the `*_Map` functions in our workflows. New steps in YAML to replace `AE_MapRaw()` would look something like this:

```
steps:
  - name: RunQuery
    output: dfSUBJ
    params:
      df: dfSUBJ
      lMapping: lMapping
      strQuery: "SELECT * FROM df WHERE {`dfSUBJ$strEnrollCol`} == {`dfSUBJ$strEnrollVal`}"
  - name: RunQuery
    output: dfDenominator
    params:
      df: dfSUBJ
      lMapping: lMapping
      strQuery: "SELECT * FROM df"
  - name: RunQuery
    output: dfNumerator
    params:
      dfs: dfAE
      lMapping: lMapping
      strQuery: "SELECT * FROM df"
  - name: Make_Input_Rate
    output: dfInput
    params:
      dfs:
        - dfSubjects: dfSUBJ
        - dfNumerator: dfNumerator
        - dfDenominator: dfDenominator
      lMapping: lMapping
      lDomains: 
        - dfSubjects: dfSUBJ
        - dfNumerator: dfAE
        - dfDenominator: dfSUBJ
      strNumeratorMethod: Count
      strDenominatorMethod: Sum
      strNumeratorCol: strTimeOnStudyCol
``` 

Haven't tried to run the workflow yet. Pretty sure `Run_Workflow` will need some minor updates at least. Will work on that and try this for a few KRIs next. Also need to add more stopifnot() in `Make_Input_Rate()` along with more unit tests.
