### DISCUSSION TITLE
Data Specifications in Workflows

### DISCUSSION THREAD

**Discussion by jwildfire** [Gilead-Public/gsm#1744] [General]
# Overview

As we start extending {gsm} with new apps and modules, capturing some level of data requirements is needed - especially for domain-level `mapping` data. I think there are a few ways we could do this: 

1. Extend workflows using a new `dataSpec` property or something similar
2. Use a different validation framework - maybe [json schema](https://json-schema.org/) or something from arrow/parquet ... 
3. Use an existing R package
    - [assertr](https://github.com/tonyfischetti/assertr)
    - [data.validator](https://github.com/Appsilon/data.validator)
    - [validate](https://github.com/data-cleaning/validate)
    - [pointblack](https://github.com/rstudio/pointblank)

To extend the yaml, I think capturing required tables and required/optional columns is probably sufficient.  To start very simple, we could add the following to `kri0001.yaml` (the AE KRI) to indicate the required columns: 

```
spec: 
  dfAE:
    - subjid
  dfEnrolled:
    - subjid
    - invid
    - timeonstudy  
```

Tracking required/optional columns would be slightly more complex. We could just add a string (or boolean) to each column, or we could make a more complex object. 

```
# With string
spec: 
  dfAE:
    subjid: required
  dfEnrolled:
    subjid: required
    invid: optional
    timeonstudy: optional

# With Boolean
spec: 
  dfAE:
    subjid: TRUE
  dfEnrolled:
    subjid: TRUE
    invid: FALSE
    timeonstudy: FALSE

# with a required property (Also allows typing, etc
spec: 
  dfAE:
    subjid:
       required: TRUE
       type: string
...
```

Leaning towards option #1 as a baseline implementation. Will prototype something ASAP.
