### DISCUSSION TITLE
Refactor Mapping yaml

### DISCUSSION THREAD

**Discussion by jwildfire** [Gilead-Public/gsm#1771] [Ideas]
# Overview

Consider refactoring the `inst/data_mapping.yaml` workflow to incorporate the new `spec` property and more easily support data-requirements from multiple modules/reports.

# Current Implementation

Currently `data_mapping.yaml` uses `RunQuery()` to execute a series of simple sql commands. including: 
- "SELECT subjectname as subject_nsv, * FROM df WHERE data_entry_lag > 10"
-  "SELECT subjectenrollmentnumber as subjid, * FROM df WHERE deemedimportant == 'Yes'"

The current implementation includes the following: 
1. Selecting columns
2. Renaming columns
3. Filtering based on a single value
4. Filtering based on multiple values
5. Filtering based on a numeric comparison
6. Filtering on multiple conditions

# Possible Refactor

Provide a machine-readable specification (YAML/List) that would easily allow requirements from multiple modules to be combined in to a single mapping step. We'd need to support all 6 use cases above (and possibly others).  Select and Rename (1. and 2. above) can probably be accomplished using the current `spec` objects. We'd just need to add an optional `rename` parameter for each required column. 

Adding filters is also pretty straightforward, I think. For example, the current implementation of `Mapped_Enrolled`: 

```
spec:
  Raw_SUBJ:
      subjectid:
        required: true
      enrollyn:
        required: true
steps: 
  - name: RunQuery
    output: Mapped_Enrolled
    params:
      df: Raw_SUBJ
      strQuery: "SELECT subjectid as raw_subjectid, * FROM df WHERE enrollyn == 'Y'"
```

becomes: 

```
spec:
  Raw_SUBJ:
      _filters:
        - "enrollyn == 'Y'"
      subjectid:
        required: true
        rename: raw_subjectid
      enrollyn:
        required: true
steps: 
  - name: RunQuery
    output: Mapped_Enrolled
    params:
      df: Raw_SUBJ
     spec: spec
```

`RunQuery` then gets a refactor to parse `{spec$df}` into a query. We can discuss whether to stick with SQL or change to DuckDB or just use dplyr. 

In fact, we can just create `RunQueries()` that loops through `spec` and calls `RunQuery` for each element: 

```
steps:
   - name: RunQueries
   - output: lMapped
   - params: 
      - lData: raw_data
      - lSpec: spec
```
