### DISCUSSION TITLE
Valtools design questions

### DISCUSSION THREAD

**Discussion by jwildfire** [Gilead-Public/gsm#222] [General]
@kodesiba @mattroumaya Reading through the validation PR, I had a few thoughts that we may want to bring up regarding valtools. If these comments actually make sense (and don't just represent confusion on my part) we may want to discuss with Eli and the valtools team (and perhaps offer to collaborate on a PR or 2). 

- I really don't like having the test code sitting nested in the vignettes folder. See https://github.com/phuse-org/valtools/issues/215. Would like to have an option to save test code in `tests\valtools` or something similar. 
- I find the markdown formatting for requirements and test cases to be a bit cumbersome (but not unworkable). I expect these are designed to support the workflow using the helper functions.
- I find it hard to fully keep track of which requirement maps to which test case, since they are never really documented side-by-side. Even the final pdf never really makes this easy to track.
- I feel like this process is begging for a machine readable configuration file. YAML/List Something like:

```
AE_Assess:
  Specifications:
    - S1.1:
       Description: Given correct input data an Adverse Event assessment can be done using the poisson method
       Risk: High
       Impact: Low
    - S1.2:
  Test Cases:
    - T1.1:
        Description: Test that the AE assessment can return a correctly assessed data frame for the poisson test grouped by the study variable when given correct input data
       Coverage: 
          - S1.1
          - S1.2
          - S1.3
     - T1.2:
```
     
Maybe this is happening behind the scenes already?

**Comment by jwildfire** [comment]
After reading the valtools docs a bit more, I'm seeing a major focus on tracking authorship and change logs. Since we're already using Git/Github, I'm honestly not sure there is much of a value add for us there. I think a bit scraping some PR metadata with the github API gets us most of what we need, and then we still always have `git log` and `git blame` for an audit or more granular reporting needs.

**Comment by jwildfire** [comment]
I guess after this deep dive, I'm leaning towards removing {valtools} in lieu of a custom qualification workflow that does the following: 
- Documents Specs and Test Cases in some kind of standard machine readable format (like the YAML above?). 
    - Probably at `inst/qualification/specs.yaml`.
    - Or maybe one file per assessment is better: `inst/qualification/AE_specs.yaml`
- Create custom tests for each test case in using the standard testthat workflow. e.g. `tests/testthat/test_t1_1.R` has the test code for `T1.1`
- Create a report that parses the links Specs/Test Cases and links to the test code.
   - I would probably just create markdown/html via a GitHub action and not bother with forcing it in to a vignette.
   - Could still consider linking to it from Readme/pkgdown.

**Comment by jwildfire** [comment]
Refining this a bit further. Specs live in `inst/specs/` and look like this: 

```
S1_1: 
       Description: Given correct input data an Adverse Event assessment can be done using the poisson method
       Risk: High
       Impact: Low
       Tests: 
           - T1_1 
           - T1_2
S1_2:
   ...
```

Each test lives in its own file in `tests/testthat` and has the naming convention `test_qual_T1_1.R` and contain a single test_that() call:

```
test_that("AE assessment can return a correctly assessed data frame for the poisson test grouped by the study variable when given correct input data Coverage",{
   #Test code goes here
})
