### DISCUSSION TITLE
StudyAssess() Dev notes

### DISCUSSION THREAD

**Discussion by jwildfire** [Gilead-Public/gsm#336] [General]
# Issues to create

- [x]  Add new filter utility function to be used for both population and domain-level filters
- [x]  Refactor `is_mapping_valid` to more easily utilize a single mapping object. 
- [x] Add check that expected data domains are provided in Study_Assess
- [x] Add basic tests and docs for makeAssessmentList
- [x] Build out unit tests for core functionality in runAssessment, Study_Assess, Study_AssessmentReport, Study_Report and Study_Table

# Todos
- [x] More robust `makeAssessmentList()`
- [ ] Check to make sure lPopFlag columns are found in lData$subj
- [ ] Check to make sure that assessment$filter columns are found in specified domain data
- [ ] Use mapping to specify filter value in assessement$filter list (e.g. for treatment emergent AEs `strTECol : strTEVal`)
- [x] Standardize capitalization in `clindata::mapRawPlus` and sync `rawplus.yaml`

- [x] Create standalone `Run_Assessment` function that gets called by `Study_Assess`
- [ ] Make tests for util-makeAssessmentList
- [x] Make report that can stack `is_mapping_valid()$tests_if`

# Possible Issues in Other functions
- [x] Update mapping functions to use rawplus for domain level data.
    - use strIDCol = SubjectID for dfAE 
- [ ] Use metadata for the detault mapping in X_Map_Raw
- [x] Rename dfRDSL to dfSubj in all map functions
- [x] Only check data for existence of columns specified in vRequiredParams in is_mapping_valid (#338)
- [ ] Add checks for updates in #338
- [x] Use `strTimeOnTreatment` or `strTimeOnStudy`  instead of `strExposureCol` in `X_Map_Raw`
- [ ] Standardize `util` naming
- [ ] Add bQuiet in mapping functions
- [ ] silence messages in testthat files

**Comment by jwildfire** [comment]
Thinking about moving to a yaml that looks more like this: 

```
label: Treatment-Emergent Adverse Events 
assessment: AE
workflow:
  Filter: 
    dfAE:
      strTreatementEmergentCol: TRUE
  Map_Raw: 
    functionName: AE_Map_Raw
    params:
      - dfAE
      - dfSUBJ
      - mapping: 
        dfAE: 
          - strIDCol
        dfSUBJ: 
          - strIDCol
          - strSiteCol
          - strTimeOnTreatmentCol 
  Assess:
    functionName: AE_Assess
    params:
      bMethod: Poisson
  Visualize: 
    functionName: Visualize_Scatter
    params: 
      - dfSummary
```

**Comment by jwildfire** [comment]
Another iteration of a spec: 
```
label: Treatment-Emergent Adverse Events 
tags:
  Assessment: Safety
  Label: AEs
workflow: 
  Filter_Domain:
     data: 
       dfAE:
        - strIDCol
        - strTreatementEmergentCol
       params: NULL

  AE_Map_Raw: 
    data: 
      dfAE:
        - strIDCol
      dfSUBJ: 
        - strIDCol
        - strSiteCol
        - strTimeOnTreatmentCol 
   AE_Assess:
     data: 
       dfInput: 
         - strIDCol : SubjectID
         - strExporusureCol : ...
       params: 
           method: Wilcoxon
```
