### DISCUSSION TITLE
Workflow updates to support Stratified KRIs

### DISCUSSION THREAD

**Discussion by jwildfire** [Gilead-Public/gsm#533] [Ideas]
# Overview

It will be fairly common to run a stratified version of a Site-level KRI. For example, looking at PD/Month for each type of PD, or looking at AE/Month for each System Organ Class. 

One way to implement would be to add support for an optional `group` parameter in `inst/specifications/*.yaml` that specifies  a domain and column to be used for a stratified analysis. If a group is specified, the Assessment Workflow is run once per level of the specified variable. Results are returned as a named list, with each a separate assessment (with a unique set of lTags) returned for each level of the stratification variable. 

A spec for an "AE by SOC" Assessment might look like: 

```
label: Treatment-Emergent Adverse Events by SOC
tags:
  Assessment: Safety
  Label: AEs
group: 
   domain: dfAE
   column: strSystemOrganClassCol 
workflow:
   # Same as AE Workflow
```
